# this is the file for nodejs image
FROM ubuntu

MAINTAINER anil  anilsurfexel@gmail.com

RUN \ 
   apt-get  update -y && \
   apt-get install nodejs -y && \
   node -v && \
   apt-get install npm -y && \
   rm -rf /var/lib/apt/lists/*
